<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-6VFFB5C" failures="1" tests="1" name="Test" time="13.831" errors="0" timestamp="2024-06-26T22:15:52 IST">
  <testcase classname="TestCases.QaLegend_TestCases" name="sendAMessage" time="7.192">
    <failure type="java.lang.AssertionError" message="expected [Testmessage3142] but found [Devika M
Today at 04:45 pm]">
      <![CDATA[java.lang.AssertionError: expected [Testmessage3142] but found [Devika M
Today at 04:45 pm]
at TestCases.QaLegend_TestCases.sendAMessage(QaLegend_TestCases.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- sendAMessage -->
  <testcase classname="TestCases.QaLegend_TestCases" name="addEditNotes" time="0.0">
    <ignored/>
  </testcase> <!-- addEditNotes -->
  <testcase classname="TestCases.QaLegend_TestCases" name="loginToQaLegendApp" time="0.0">
    <ignored/>
  </testcase> <!-- loginToQaLegendApp -->
  <testcase classname="TestCases.QaLegend_TestCases" name="forgotPasswordVerification" time="0.0">
    <ignored/>
  </testcase> <!-- forgotPasswordVerification -->
</testsuite> <!-- Test -->
